### PR TITLE
Update dependencies

### LINKED ISSUE #3: Actively Maintained?
Hey, I'm thinking about using this library for a project at work. Since it's been a while since this project has merged a PR I just wanted to check if there was an active desire to maintain it. I'd be happy to do some PRs to update dependencies (ie using `amqp_client 3.6.X` branch), and make the configurable number of consumers work.

I just wanted to check whether there is an active set of maintainers here before I invested the time.

### PR DESCRIPTION
**Pull request by mmmries**
Resolves #3 

This is an attempt to do a minimal pass at bringing `fireworks` up to date with the `amqp_client` and the elixir `1.4.X` releases. It uses explicit parentheses and replaces an assignment inside of a conditional with an explicitly returned value.

### CODE REVIEW

**Comment by mmmries** [comment]
@mobileoverlord do you know if this library is still used at LiveHelpNow? Do you think it would be better to just fork the library at this point? Do you have any interest in maintaining it?

**Comment by mobileoverlord** [comment]
I believe it is. @ewitchin said he would take a peek at these and get them merged in.

**Comment by ewitchin** [comment]
Sorry for the delay in response and thanks for pushing updates!

**Comment by mmmries** [comment]
❤️ 💛 💙 💚  No problem! I'll gladly keep pushing updates if you find them useful. I'm planning to add it more complete support for doing multiple consumers and possibly allowing binding of multiple queues to a single consumer so users can have a bunch of queues feed into a single "thread pool" and control the concurrency that way.

Are these types of changes welcome to this project?

**Comment by ewitchin** [comment]
We welcome any enhancements to the project! Our current use for it only needs the singular binding, but expanding it to work with 1 or more would be great.

**Pull request merged**
